apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceph-mgr
  namespace: ${namespace}
  labels:
    app: ceph-mgr
spec:
  selector:
    matchLabels:
      app: rook-ceph-mgr
  namespaceSelector:
    matchNames:
      - rook-ceph
  endpoints:
  - port: http-metrics
    interval: 15s
    path: /metrics
