apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubeflow-katib
  namespace: ${namespace}
  labels:
    app: kubeflow-katib
spec:
  selector:
    matchLabels:
      app: katib-controller
  namespaceSelector:
    matchNames:
      - kubeflow
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
