apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubeflow-training-operator
  namespace: ${namespace}
  labels:
    app: kubeflow-training
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: training-operator
  namespaceSelector:
    matchNames:
      - kubeflow
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
