apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-console
  namespace: monitoring
  labels:
    app: minio-console
spec:
  selector:
    matchLabels:
      app: minio-console
  namespaceSelector:
    matchNames:
      - minio-operator
      - minio-tenant
      - minio
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
