apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mlflow-server
  namespace: ${namespace}
  labels:
    app: mlflow
    component: server
spec:
  selector:
    matchLabels:
      app: mlflow
      component: server
  namespaceSelector:
    matchNames:
      - mlflow
  endpoints:
  - port: prometheus
    interval: 15s
    path: /metrics
