apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceph-osd
  namespace: monitoring
  labels:
    app: ceph-osd
spec:
  selector:
    matchLabels:
      app: rook-ceph-osd
  namespaceSelector:
    matchNames:
      - rook-ceph
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
