apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubeflow-pipeline
  namespace: monitoring
  labels:
    app: kubeflow-pipeline
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-pipeline
  namespaceSelector:
    matchNames:
      - kubeflow
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
