expose:
  type: loadBalancer
  tls:
    enabled: true
    certSource: auto
    auto:
      commonName: "harbor.local"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 50Gi
      storageClass: "local-path"
    jobservice:
      size: 10Gi
      storageClass: "local-path"
    database:
      size: 5Gi
      storageClass: "local-path"
    redis:
      size: 5Gi
      storageClass: "local-path"
    trivy:
      size: 5Gi
      storageClass: "local-path"

harborAdminPassword: "@7T2W%bwW9Qm#Mh4"
